### ISSUE TITLE
var jsVar = "123.docx"; builder. SaveFile ("docx", jsValue (jsVar));  //run error

### ISSUE THREAD

**Issue by sdmq** [ONLYOFFICE/DocumentBuilder#101] opened 2023-03-30 10:54 UTC
Docbuilder.exe  V7.3.3  when executed docbuilder file

builder.CreateFile("docx");
var jsVar = "123.docx";
builder. SaveFile ("docx", jsValue (jsVar));
builder.CloseFile();

// run error(error: : save file error (-1073741819))

**Comment by NilKu** [comment] 2023-08-01 05:36
Docbuilder.exe V7.4.0 on Windows
```js
var a = "any text"; 
builder.CreateFile("docx");
builder.SaveFile("pdf", "d:\empty.pdf", "");
builder.CloseFile();
```
`error (command): file not opened!`

however the following script works
```js
builder.CreateFile("docx");
builder.SaveFile("pdf", "d:\empty.pdf", "");
builder.CloseFile();
```

**Comment by askonev** [comment] 2023-08-28 18:57
I can confirm - this is `bug #59905`

**Comment by askonev** [comment] 2024-01-17 11:42
builder - is needed to NOT use js in the script. Then the script will be executed faster, because it will just be conversion. If js is present, it is easier to write like this (js variables are fully working)

[builderJS](https://api.onlyoffice.com/docbuilder/integrationapi/default#:~:text=The%20entire%20JavaScript%20context%20is%20a%20wrapper%20for%20its%20native%20CDocBuilder%20builderJS%20object.%20You%20need%20to%20work%20with%20it%20as%20with%20an%20ordinary%20JavaScript%20object.%20In%20this%20case%2C%20the%20jsValue%20instruction%20is%20not%20needed%20for%20the%20JS%20variables%3A)

```js
builderJS.CreateFile("docx");
var jsVar = "test.docx";
builderJS.SaveFile("docx", jsVar);
```

**Comment by Rita-Bubnova** [comment] 2024-08-06 13:18
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-08-06 13:18 UTC
Labels: confirmed-bug, invalid
